version: '3.8'

services:
  server:
    image: server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "55000:55000"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:55000"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  client:
    image: client
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - mynetwork
    depends_on:
      - server

networks:
  mynetwork:
    driver: bridge