version: '3.8'

services:
  server:
    image: server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "55000:55000"
    command: ./build/boost_server

  client:
    image: client
    build:
      context: .
      dockerfile: Dockerfile.client
    command: ./build/boost_client
    network_mode: host
    depends_on:
      - server